Add `inputmode` and `spellcheck` to input component nunjucks macro
nhsuk/nhsuk-frontend pull request #666
Opened 2020-12-09 10:41 UTC by davidhunter08

## Description

Add `inputmode` and `spellcheck` to input component nunjucks macro.

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

2020-12-11 14:55 UTC, mcheung-nhs requested changes
Need to update the README for date-input for the HTML markup to change the `type="number"`
https://github.com/nhsuk/nhsuk-frontend/blob/input-component-macro/packages/components/date-input/README.md

2020-12-11 15:07 UTC, davidhunter08 commented
> Need to update the README for date-input for the HTML markup to change the `type="number"`
> https://github.com/nhsuk/nhsuk-frontend/blob/input-component-macro/packages/components/date-input/README.md

Thanks @mcheung-nhs. I've made those changes.

2020-12-11 15:18 UTC, mcheung-nhs commented
Hi @davidhunter08 - can see the requested changes - thanks! Do we also need to add the `type="text"` in the HTML as that is what is output, from the macro 
`type="{{ params.type | default('text') }}"`

2020-12-11 15:24 UTC, davidhunter08 commented
> Hi @davidhunter08 - can see the requested changes - thanks! Do we also need to add the `type="text"` in the HTML as that is what is output, from the macro
> `type="{{ params.type | default('text') }}"`

Yep, you're right. I've made the changes.

2020-12-11 17:44 UTC, mcheung-nhs approved these changes

2020-12-11 17:44 UTC, merged

2021-09-09 09:00 UTC, kevinkuszyk commented
@davidhunter08 I may be a little late to the party here, but what's the rationale for using `type="text"` instead of `type="number"`?

Not only does it feel semantically incorrect, but you also lose some browser features (up / down arrow support on the keyboard and spinners in the UI).

We're catching up with these changes in the react components☝️,  and before we apply I like to understand the context a little better.

Thanks!

/cc @KaiSpencer @Tomdango @frobernik

2021-09-09 09:04 UTC, mcheung-nhs commented
Hi @kevinkuszyk, we were following guidance and research done by gov.uk:
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

2021-09-09 09:05 UTC, andymantell commented
@kevinkuszyk The rationale for this can be found here:

https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

2021-09-09 14:40 UTC, kevinkuszyk commented
Thanks @mcheung-nhs - that's exactly what I was looking for.