Vendor in Sass-Mq dev to master
nhsuk/nhsuk-frontend pull request #685
Opened 2021-01-18 19:35 UTC by AdamChrimes

## Description

#601 merged to `dev` branch to test the change, now ready for `master`

2021-01-18 20:01 UTC, mcheung-nhs requested changes

2021-01-18 20:01 UTC, mcheung-nhs commented on packages/core/tools/_sass-mq.scss
> +// incase node_modules is not installed in the folder relative to the root folder
@AdamChrimes - sorry to be pedantic but should this be "in case"?

2021-01-19 08:51 UTC, AdamChrimes commented
Fixed @mcheung-nhs

2021-01-19 09:09 UTC, mcheung-nhs approved these changes
LGTM

2021-01-19 09:23 UTC, merged