Alpha v7
nhsuk/nhsuk-frontend pull request #831
Opened 2022-07-20 13:28 UTC by wa-rren-dev

## Description

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

2022-08-08 19:49 UTC, kevinkuszyk commented
@wa-rren-dev do you have an ETA for shipping the final v7, and any idea of milestones along the way?

I'm looking forward to no longer seeing all the SASS errors when we build our app, and I'll also try and keep [NHSDigital/nhsuk-react-components](https://github.com/NHSDigital/nhsuk-react-components) in sync if you have a roadmap you can publish.

Thanks, and as always, keep up the good work!

2022-08-09 10:00 UTC, wa-rren-dev commented
Cheers @kevinkuszyk, we don't have a release plan just yet as we're running with a skeleton crew at the moment, but the alpha is an attempt to get some momentum going. The main barrier to getting it released will be the production of the guidelines to go in the service manual for the new components, but if it comes to it we could possibly release a more reliable beta version of v7 with assurances that there won't be any sweeping changes.

2022-08-11 14:41 UTC, andymantell commented
Hi Adam,

1. Good question. It was grey originally and I switched it because it "looked funny" in the demos. But that's not really a great reason, and I do note the govuk one is grey. See before and after below. What do you think, should we put it back to grey? Or maybe make grey the default but have a modifier which gives you white tabs, in case that makes more sense in whatever context people put it in?

Now that I've written all that, I'm leaning towards just making it grey - to match the govuk one as you say. Can I get another opinion @wa-rren-dev ?

![image](https://user-images.githubusercontent.com/134642/184159489-81958b6a-a8b8-40a7-8878-c67c67cc5f06.png)

2. It should be left aligned - that's a bug in the version you've got there. Have you updated recently? This should have been fixed by 336c98ae3869abc94ffde1222a474f812bfc3f95

2022-08-11 14:50 UTC, andymantell commented
Sorry, the actual commit that fixed the tab alignment was this:

https://github.com/nhsuk/nhsuk-frontend/pull/831/commits/43f4fa5f901568c50619e4d26be48ec6a1158c62#diff-92bf1bf018dd660a48623539ce33dd98f218877144e4f6beb606693c46e8b4fa

2022-08-11 19:44 UTC, chrimesdev commented
Thanks @andymantell I can see what you mean. I think white Cards (and other colored components) can often be overused on NHS pages, as they stand out more, so it might convey more importance than the content on the rest of the page as I think you're more drawn to it. I'll speak to our designer tomorrow and see what he thinks. 

If it helps here's a screenshot of a Figma design with the Tabs with a grey background in a real scenario:

<img width="458" alt="Screenshot 2022-08-11 at 20 42 42" src="https://user-images.githubusercontent.com/11615501/184225750-dc8146c0-e981-430e-bffe-59fd15d2a410.png">

2022-08-16 11:39 UTC, wa-rren-dev commented
Regarding the tab backgrounds - I wouldn't like to make any particular suggestion! It really needs design and UR around it. 

That said, my personal preference would be to keep the tabs white. Without the background it can be hard when scanning to see what is part of a tab's content and what is proceeding page content.

Hopefully this sort of thing will be picked up in the forthcoming tabs work that mission team 1 are planning on doing. Have referenced this thread in the [assosciated epic](https://github.com/nhsuk/nhsuk-service-manual/issues/1790).

2022-08-17 08:56 UTC, chrimesdev commented
Thanks @andymantell and @wa-rren-dev! We've just gone live with the Tabs component (https://www.demo.livi.thirdparty.nhs.uk/services/order-a-repeat-prescription/) will let you know how it goes!

2022-08-17 09:02 UTC, wa-rren-dev commented
> Thanks @andymantell and @wa-rren-dev! We've just gone live with the Tabs component (https://www.demo.livi.thirdparty.nhs.uk/services/order-a-repeat-prescription/) will let you know how it goes!

Great, any feedback you get do send it back round if you can!

2022-08-22 15:14 UTC, chrimesdev commented
Is the `[7.0.0-alpha.2](https://www.npmjs.com/package/nhsuk-frontend/v/7.0.0-alpha.2)` package ready/safe to be used in production services? Is it being used on any other live services currently?

2022-08-23 08:55 UTC, wa-rren-dev commented
Hi @chrimesdev, not being used on any live services that I'm aware of. Based on the pace of change so far I wouldn't recommend using it in production unless you're happy to pin the alpha version you're using in your dependencies. I really can't imagine anything else breaking at this point but based on the possibility that this alpha might outlive all of us, I wouldn't let it auto install the latest version. We're trying to retain the ability to still make sweeping changes at this point.

2023-03-06 16:17 UTC, mcheung-nhs requested changes

2023-03-10 13:52 UTC, andymantell commented on packages/components/warning-callout/README.md
> +      <span class="nhsuk-u-visually-hidden">Important:</span>
nbsp maybe?

2023-03-10 14:02 UTC, andymantell requested changes
Steal prettier config from here: https://github.com/alphagov/govuk-frontend/blob/main/.prettierrc.js

2023-03-13 17:51 UTC, andymantell commented on packages/components/tables/README.md
> +{% from 'components/tables/macro.njk' import table %} {{ table({ panel: false, caption: "Skin symptoms and possible
Agreed - I am going to revert markdown files to their master state, prevent prettier from formatting embedded code examples and then reformat them. This one is a bit nasty - it's trying to format it as html which it isn't

2023-03-13 17:55 UTC, andymantell commented on docs/installation/installing-compiled.md
> +   <link rel="stylesheet" href="css/nhsuk-[latest version].min.css" />
have reverted this in the markdown files

2023-03-13 18:02 UTC, andymantell commented on packages/components/tabs/template.njk
> +  <h2 class="nhsuk-tabs__title">
Agreed, would be a good enhancement

2023-03-13 18:04 UTC, andymantell commented on packages/components/warning-callout/README.md
> +      <span class="nhsuk-u-visually-hidden">Important:</span>
Space has been reinstated

2023-03-13 18:08 UTC, andymantell commented on packages/components/character-count/README.md
> +| **autocomplete**         | string | No       | Attribute to [identify input purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html), for instance "postal-code" or "usernam
No that's slipped in by mistake from the textarea docs, I'll remove it

2023-03-13 18:23 UTC, andymantell commented on app/components/all.njk
>  {% from 'components/contents-list/macro.njk' import contentsList %}
Yeah good shout - done.

2023-03-20 18:51 UTC, andymantell submitted a review, later dismissed

2023-03-21 09:29 UTC, mcheung-nhs requested changes

2023-03-21 10:09 UTC, andymantell commented on CHANGELOG.md
> +- Pinned the Node version to the latest LTS version at the time of publishing (16.16.0). In environments where Volta is installed the appropriate version will be used
Resolved - I linked to Prettier but removed Volta as discussed.

2023-03-21 10:13 UTC, mcheung-nhs approved these changes

2023-03-21 10:14 UTC, merged