Add open param to details nunjucks component
nhsuk/nhsuk-frontend pull request #857
Opened 2023-02-09 09:31 UTC by fofr

## Description

Fixes #856 

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [x] CHANGELOG entry

2023-02-16 10:41 UTC, tvararu approved these changes

2023-03-22 08:56 UTC, andymantell approved these changes

2023-03-22 09:42 UTC, mcheung-nhs requested changes

2023-03-22 09:42 UTC, mcheung-nhs commented on CHANGELOG.md
> +- Adds missing `open` and `id` parameters to `details` nunjucks component #856
Hi - can we link to issue 856 here:
([Issue 856](https://github.com/nhsuk/nhsuk-frontend/issues/856))
Thanks!

2023-03-22 09:46 UTC, mcheung-nhs approved these changes

2023-03-22 09:54 UTC, merged