Header and width containers margin
nhsuk/nhsuk-frontend pull request #902
Opened 2023-11-13 12:28 UTC by diana-nita

## Description

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

2023-11-13 13:41 UTC, the-nathan-smith approved these changes

2023-11-13 14:14 UTC, andymantell requested changes
I assume this is in reference to #901? Is this the right way to fix this? Feels like maybe the bug should be fixed in the header component, and not by modifying the generic width container? Happy to be wrong - dismiss my review if this has already been discussed - just concerned that it feels like quite a sweeping change across the board, to fix a specific issue in one component.

2023-11-15 13:41 UTC, andymantell approved these changes

2023-11-16 13:58 UTC, pflynny approved these changes
LGTM 🙌

2023-11-16 14:16 UTC, merged

2023-11-17 13:18 UTC, paulrobertlloyd commented
Thanks all!